/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_konteno_ao_mrover_lidar_YdLidarX4 */

#ifndef _Included_de_konteno_ao_mrover_lidar_YdLidarX4
#define _Included_de_konteno_ao_mrover_lidar_YdLidarX4
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_konteno_ao_mrover_lidar_YdLidarX4
 * Method:    init
 * Signature: (Ljava/lang/String;IIII)V
 */
JNIEXPORT void JNICALL Java_de_konteno_ao_mrover_lidar_YdLidarX4_init
  (JNIEnv *, jobject, jstring, jint, jint, jint, jint);

/*
 * Class:     de_konteno_ao_mrover_lidar_YdLidarX4
 * Method:    scan
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_de_konteno_ao_mrover_lidar_YdLidarX4_scan
  (JNIEnv *, jobject);

/*
 * Class:     de_konteno_ao_mrover_lidar_YdLidarX4
 * Method:    turnOn
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_konteno_ao_mrover_lidar_YdLidarX4_turnOn
  (JNIEnv *, jobject);

/*
 * Class:     de_konteno_ao_mrover_lidar_YdLidarX4
 * Method:    turnOff
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_konteno_ao_mrover_lidar_YdLidarX4_turnOff
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
